### ISSUE TITLE
Write blog post on lesser known features of NUSMods

### ISSUE THREAD

**Issue by yangshun** [nusmodifications/nusmods-blog#1]
Points I intend to cover:
- Dark mode and theme colors
- Sharing and exporting of timetable
- Bookmark modules
- Navigation shortcuts for power users
- Venue availability
- CORS history (reference first blog post)

Any comments/suggestions before I start writing? @xinan @ahbeng @ngzhian

**Comment by ngzhian** [comment]
Yea that sounds good! I wonder what people don't know about tho, e.g. i think exports are pretty well known, whereas navigation isn't that well known.
I personally thing the most useful thing will be:
1. Dark mode and theme colors
2. navigation short cuts
3. cors history
